### ISSUE TITLE
Learn to write good commit message and description

### ISSUE THREAD

**Issue by webknjaz** [kpi-web-guild/django-girls-blog-wack17s#2]
![](http://software-engineer-training.com/wp-content/uploads/2009/08/overlord59-tux-samourai.png)

According to common commit style guides it is required to write messages in imperative manner. Make them actionable. Also **avoid using `-m`** as you often need to express more detail in a long way. Here's several articles sharing best practices:
* [x] http://chris.beams.io/posts/git-commit/
* [x] http://alistapart.com/article/the-art-of-the-commit
* [x] https://robots.thoughtbot.com/5-useful-tips-for-a-better-commit-message
* [x] https://github.com/erlang/otp/wiki/writing-good-commit-messages
* [x] https://wiki.openstack.org/wiki/GitCommitMessages
* [x] http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
* [x] https://dev.to/gonedark/when-to-make-a-git-commit
Please read at all of them :)

N.B. This all applies to [issues](https://github.com/kpi-web-guild/django-girls-blog-wack17s/issues/new) and [PRs](https://github.com/kpi-web-guild/django-girls-blog-wack17s/compare).

**Comment by wack17s** [comment]
Done.
