### ISSUE TITLE
Add basic configuration and info files

### ISSUE THREAD

**Issue by webknjaz** [kpi-web-guild/django-girls-blog-wack17s#3]
* [x] `README.md`, stating your project title, styled with Markdown
* [x] `LICENSE` file. Find template for it in plain text or Markdown format. You may use MIT licence for simplicity
* [x] `.gitattributes`. Find some template for your repo on github
* [x] `.gitignore`. Find typical template for your language

**Comment by wack17s** [comment]
@webknjaz PR [#11](https://github.com/kpi-web-guild/django-girls-blog-wack17s/pull/11)

**Comment by webknjaz** [comment]
@wack17s plz include `Closes #3` in PR, so that merging it would automatically trigger closing this issue.
